name = "weathernow-kim-precompute"
main = "workers/kim-precompute.js"
compatibility_date = "2026-07-22"

[triggers]
crons = ["*/5 * * * *"]

[vars]
KIM_PRECOMPUTE_BATCH_SIZE = "1"
KIM_RETAINED_CYCLES = "3"

[[kv_namespaces]]
binding = "KIM_RAIN_CACHE"
id = "61c05160529a48628ff953ec14ae6049"
